# House-Price-Model(Linear Regression)

## Importing modules

In [1022]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

## Reading File

In [1023]:
train=pd.read_csv('F:/Master SEM-2/dsp-yashkumar-jain/data/house-prices-advanced-regression-techniques/train.csv')
test=pd.read_csv('F:/Master SEM-2/dsp-yashkumar-jain/data/house-prices-advanced-regression-techniques/test.csv')

In [1024]:
train.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

In [1025]:
test.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition
0,1461,20,RH,80.0,11622,Pave,NaN,Reg,Lvl,AllPub,...,120,0,NaN,MnPrv,NaN,0,6,2010,WD,Normal
1,1462,20,RL,81.0,14267,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,Gar2,12500,6,2010,WD,Normal
2,1463,60,RL,74.0,13830,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,MnPrv,NaN,0,3,2010,WD,Normal
3,1464,60,RL,78.0,9978,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,6,2010,WD,Normal
4,1465,120,RL,43.0,5005,Pave,NaN,IR1,HLS,AllPub,...,144,0,NaN,NaN,NaN,0,1,2010,WD,Normal

In [1026]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 81 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             1460 non-null   int64
 1   MSSubClass     1460 non-null   int64
 2   MSZoning       1460 non-null   object
 3   LotFrontage    1201 non-null   float64
 4   LotArea        1460 non-null   int64
 5   Street         1460 non-null   object
 6   Alley          91 non-null     object
 7   LotShape       1460 non-null   object
 8   LandContour    1460 non-null   object
 9   Utilities      1460 non-null   object
 10  LotConfig      1460 non-null   object
 11  LandSlope      1460 non-null   object
 12  Neighborhood   1460 non-null   object
 13  Condition1     1460 non-null   object
 14  Condition2     1460 non-null   object
 15  BldgType       1460 non-null   object
 16  HouseStyle     1460 non-null   object
 17  OverallQual    1460 non-null   int64
 18  OverallCond    1460 non-null   int64
 19  YearBuilt      1460 non-null   int64
 20  YearRemodAdd   1460 non-null   int64
 21  RoofStyle      1460 non-null   object
 22  RoofMatl       1460 non-null   object
 23  Exterior1st    1460 non-null   object
 24  Exterior2nd    1460 non-null   object
 25  MasVnrType     1452 non-null   object
 26  MasVnrArea     1452 non-null   float64
 27  ExterQual      1460 non-null   object
 28  ExterCond      1460 non-null   object
 29  Foundation     1460 non-null   object
 30  BsmtQual       1423 non-null   object
 31  BsmtCond       1423 non-null   object
 32  BsmtExposure   1422 non-null   object
 33  BsmtFinType1   1423 non-null   object
 34  BsmtFinSF1     1460 non-null   int64
 35  BsmtFinType2   1422 non-null   object
 36  BsmtFinSF2     1460 non-null   int64
 37  BsmtUnfSF      1460 non-null   int64
 38  TotalBsmtSF    1460 non-null   int64
 39  Heating        1460 non-null   object
 40  HeatingQC      1460 non-null   object
 41  CentralAir     1460 non-null   object
 42  Electrical     1459 non-null   object
 43  1stFlrSF       1460 non-null   int64
 44  2ndFlrSF       1460 non-null   int64
 45  LowQualFinSF   1460 non-null   int64
 46  GrLivArea      1460 non-null   int64
 47  BsmtFullBath   1460 non-null   int64
 48  BsmtHalfBath   1460 non-null   int64
 49  FullBath       1460 non-null   int64
 50  HalfBath       1460 non-null   int64
 51  BedroomAbvGr   1460 non-null   int64
 52  KitchenAbvGr   1460 non-null   int64
 53  KitchenQual    1460 non-null   object
 54  TotRmsAbvGrd   1460 non-null   int64
 55  Functional     1460 non-null   object
 56  Fireplaces     1460 non-null   int64
 57  FireplaceQu    770 non-null    object
 58  GarageType     1379 non-null   object
 59  GarageYrBlt    1379 non-null   float64
 60  GarageFinish   1379 non-null   object
 61  GarageCars     1460 non-null   int64
 62  GarageArea     1460 non-null   int64
 63  GarageQual     1379 non-null   object
 64  GarageCond     1379 non-null   object
 65  PavedDrive     1460 non-null   object
 66  WoodDeckSF     1460 non-null   int64
 67  OpenPorchSF    1460 non-null   int64
 68  EnclosedPorch  1460 non-null   int64
 69  3SsnPorch      1460 non-null   int64
 70  ScreenPorch    1460 non-null   int64
 71  PoolArea       1460 non-null   int64
 72  PoolQC         7 non-null      object
 73  Fence          281 non-null    object
 74  MiscFeature    54 non-null     object
 75  MiscVal        1460 non-null   int64
 76  MoSold         1460 non-null   int64
 77  YrSold         1460 non-null   int64
 78  SaleType       1460 non-null   object
 79  SaleCondition  1460 non-null   object
 80  SalePrice      1460 non-null   int64
dtypes: float64(3), int64(35), object(43)
memory usage: 924.0+ KB

### FInd correlation with respect to SalePrice

In [1027]:
train.corr().sort_values(by='SalePrice')['SalePrice']

KitchenAbvGr    -0.135907
EnclosedPorch   -0.128578
MSSubClass      -0.084284
OverallCond     -0.077856
YrSold          -0.028923
LowQualFinSF    -0.025606
Id              -0.021917
MiscVal         -0.021190
BsmtHalfBath    -0.016844
BsmtFinSF2      -0.011378
3SsnPorch        0.044584
MoSold           0.046432
PoolArea         0.092404
ScreenPorch      0.111447
BedroomAbvGr     0.168213
BsmtUnfSF        0.214479
BsmtFullBath     0.227122
LotArea          0.263843
HalfBath         0.284108
OpenPorchSF      0.315856
2ndFlrSF         0.319334
WoodDeckSF       0.324413
LotFrontage      0.351799
BsmtFinSF1       0.386420
Fireplaces       0.466929
MasVnrArea       0.477493
GarageYrBlt      0.486362
YearRemodAdd     0.507101
YearBuilt        0.522897
TotRmsAbvGrd     0.533723
FullBath         0.560664
1stFlrSF         0.605852
TotalBsmtSF      0.613581
GarageArea       0.623431
GarageCars       0.640409
GrLivArea        0.708624
OverallQual      0.790982
SalePrice        1.000000
Name: SalePrice, dtype: float64

### Taking features which has correlation greater than 0.6

In [1028]:
# Spearting numerical features for train
train_X_num=train[['OverallQual','GrLivArea','GarageCars','GarageArea','TotalBsmtSF','SalePrice']]
train_X_num

      OverallQual  GrLivArea  GarageCars  GarageArea  TotalBsmtSF  SalePrice
0               7       1710           2         548          856     208500
1               6       1262           2         460         1262     181500
2               7       1786           2         608          920     223500
3               7       1717           3         642          756     140000
4               8       2198           3         836         1145     250000
...           ...        ...         ...         ...          ...        ...
1455            6       1647           2         460          953     175000
1456            6       2073           2         500         1542     210000
1457            7       2340           1         252         1152     266500
1458            5       1078           1         240         1078     142125
1459            5       1256           1         276         1256     147500

[1460 rows x 6 columns]

In [1029]:
#Spearting numerical features for test
test_X_num=test[['OverallQual','GrLivArea','GarageCars','GarageArea','TotalBsmtSF']]
test_X_num.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1459 entries, 0 to 1458
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   OverallQual  1459 non-null   int64
 1   GrLivArea    1459 non-null   int64
 2   GarageCars   1458 non-null   float64
 3   GarageArea   1458 non-null   float64
 4   TotalBsmtSF  1458 non-null   float64
dtypes: float64(3), int64(2)
memory usage: 57.1 KB

## Categorical Features

In [1030]:
train_X_cat=train.select_dtypes(include=['object'])
train_X_cat.head()

,MSZoning,Street,Alley,LotShape,LandContour,Utilities,LotConfig,LandSlope,Neighborhood,Condition1,...,GarageType,GarageFinish,GarageQual,GarageCond,PavedDrive,PoolQC,Fence,MiscFeature,SaleType,SaleCondition
0,RL,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,CollgCr,Norm,...,Attchd,RFn,TA,TA,Y,NaN,NaN,NaN,WD,Normal
1,RL,Pave,NaN,Reg,Lvl,AllPub,FR2,Gtl,Veenker,Feedr,...,Attchd,RFn,TA,TA,Y,NaN,NaN,NaN,WD,Normal
2,RL,Pave,NaN,IR1,Lvl,AllPub,Inside,Gtl,CollgCr,Norm,...,Attchd,RFn,TA,TA,Y,NaN,NaN,NaN,WD,Normal
3,RL,Pave,NaN,IR1,Lvl,AllPub,Corner,Gtl,Crawfor,Norm,...,Detchd,Unf,TA,TA,Y,NaN,NaN,NaN,WD,Abnorml
4,RL,Pave,NaN,IR1,Lvl,AllPub,FR2,Gtl,NoRidge,Norm,...,Attchd,RFn,TA,TA,Y,NaN,NaN,NaN,WD,Normal

In [1031]:
train_X_cat.isnull().sum()

MSZoning            0
Street              0
Alley            1369
LotShape            0
LandContour         0
Utilities           0
LotConfig           0
LandSlope           0
Neighborhood        0
Condition1          0
Condition2          0
BldgType            0
HouseStyle          0
RoofStyle           0
RoofMatl            0
Exterior1st         0
Exterior2nd         0
MasVnrType          8
ExterQual           0
ExterCond           0
Foundation          0
BsmtQual           37
BsmtCond           37
BsmtExposure       38
BsmtFinType1       37
BsmtFinType2       38
Heating             0
HeatingQC           0
CentralAir          0
Electrical          1
KitchenQual         0
Functional          0
FireplaceQu       690
GarageType         81
GarageFinish       81
GarageQual         81
GarageCond         81
PavedDrive          0
PoolQC           1453
Fence            1179
MiscFeature      1406
SaleType            0
SaleCondition       0
dtype: int64

### Replacing null values to something meaningful

In [1032]:
def replaceNaN(df):
    df.fillna({'Alley':'No alley access',
                   'BsmtQual':'No Basement',
                   'BsmtCond':'No Basement',
                   'BsmtExposure':'No Basement',
                   'BsmtFinType1':'No Basement',
                   'BsmtFinType2':'No Basement',
                    'FireplaceQu':'No Fireplace',
                   'GarageType':'No Garage',
                   'GarageFinish':'No Garage',
                   'GarageQual':'No Garage',
                   'GarageCond':'No Garage',
                   'PoolQC':'No Pool',
                   'Fence':'No Fence',
                   'MiscFeature':'None'},
                  inplace = True)

In [1033]:
replaceNaN(train_X_cat)
train_X_cat.isnull().sum()

MSZoning         0
Street           0
Alley            0
LotShape         0
LandContour      0
Utilities        0
LotConfig        0
LandSlope        0
Neighborhood     0
Condition1       0
Condition2       0
BldgType         0
HouseStyle       0
RoofStyle        0
RoofMatl         0
Exterior1st      0
Exterior2nd      0
MasVnrType       8
ExterQual        0
ExterCond        0
Foundation       0
BsmtQual         0
BsmtCond         0
BsmtExposure     0
BsmtFinType1     0
BsmtFinType2     0
Heating          0
HeatingQC        0
CentralAir       0
Electrical       1
KitchenQual      0
Functional       0
FireplaceQu      0
GarageType       0
GarageFinish     0
GarageQual       0
GarageCond       0
PavedDrive       0
PoolQC           0
Fence            0
MiscFeature      0
SaleType         0
SaleCondition    0
dtype: int64

In [1034]:
test_X_cat=test.select_dtypes(include=['object'])
test_X_cat.head()

,MSZoning,Street,Alley,LotShape,LandContour,Utilities,LotConfig,LandSlope,Neighborhood,Condition1,...,GarageType,GarageFinish,GarageQual,GarageCond,PavedDrive,PoolQC,Fence,MiscFeature,SaleType,SaleCondition
0,RH,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,NAmes,Feedr,...,Attchd,Unf,TA,TA,Y,NaN,MnPrv,NaN,WD,Normal
1,RL,Pave,NaN,IR1,Lvl,AllPub,Corner,Gtl,NAmes,Norm,...,Attchd,Unf,TA,TA,Y,NaN,NaN,Gar2,WD,Normal
2,RL,Pave,NaN,IR1,Lvl,AllPub,Inside,Gtl,Gilbert,Norm,...,Attchd,Fin,TA,TA,Y,NaN,MnPrv,NaN,WD,Normal
3,RL,Pave,NaN,IR1,Lvl,AllPub,Inside,Gtl,Gilbert,Norm,...,Attchd,Fin,TA,TA,Y,NaN,NaN,NaN,WD,Normal
4,RL,Pave,NaN,IR1,HLS,AllPub,Inside,Gtl,StoneBr,Norm,...,Attchd,RFn,TA,TA,Y,NaN,NaN,NaN,WD,Normal

In [1035]:
replaceNaN(test_X_cat)
test_X_cat.isnull().sum()

MSZoning          4
Street            0
Alley             0
LotShape          0
LandContour       0
Utilities         2
LotConfig         0
LandSlope         0
Neighborhood      0
Condition1        0
Condition2        0
BldgType          0
HouseStyle        0
RoofStyle         0
RoofMatl          0
Exterior1st       1
Exterior2nd       1
MasVnrType       16
ExterQual         0
ExterCond         0
Foundation        0
BsmtQual          0
BsmtCond          0
BsmtExposure      0
BsmtFinType1      0
BsmtFinType2      0
Heating           0
HeatingQC         0
CentralAir        0
Electrical        0
KitchenQual       1
Functional        2
FireplaceQu       0
GarageType        0
GarageFinish      0
GarageQual        0
GarageCond        0
PavedDrive        0
PoolQC            0
Fence             0
MiscFeature       0
SaleType          1
SaleCondition     0
dtype: int64

## Concatinating train and test for encoding

In [1036]:
train_id=train_X_cat.index
test_id=test_X_cat.index
data = pd.concat([train_X_cat,test_X_cat])
data.head()

,MSZoning,Street,Alley,LotShape,LandContour,Utilities,LotConfig,LandSlope,Neighborhood,Condition1,...,GarageType,GarageFinish,GarageQual,GarageCond,PavedDrive,PoolQC,Fence,MiscFeature,SaleType,SaleCondition
0,RL,Pave,No alley access,Reg,Lvl,AllPub,Inside,Gtl,CollgCr,Norm,...,Attchd,RFn,TA,TA,Y,No Pool,No Fence,None,WD,Normal
1,RL,Pave,No alley access,Reg,Lvl,AllPub,FR2,Gtl,Veenker,Feedr,...,Attchd,RFn,TA,TA,Y,No Pool,No Fence,None,WD,Normal
2,RL,Pave,No alley access,IR1,Lvl,AllPub,Inside,Gtl,CollgCr,Norm,...,Attchd,RFn,TA,TA,Y,No Pool,No Fence,None,WD,Normal
3,RL,Pave,No alley access,IR1,Lvl,AllPub,Corner,Gtl,Crawfor,Norm,...,Detchd,Unf,TA,TA,Y,No Pool,No Fence,None,WD,Abnorml
4,RL,Pave,No alley access,IR1,Lvl,AllPub,FR2,Gtl,NoRidge,Norm,...,Attchd,RFn,TA,TA,Y,No Pool,No Fence,None,WD,Normal

In [1037]:
for col in data:
    print(data[col].unique())

['RL' 'RM' 'C (all)' 'FV' 'RH' nan]
['Pave' 'Grvl']
['No alley access' 'Grvl' 'Pave']
['Reg' 'IR1' 'IR2' 'IR3']
['Lvl' 'Bnk' 'Low' 'HLS']
['AllPub' 'NoSeWa' nan]
['Inside' 'FR2' 'Corner' 'CulDSac' 'FR3']
['Gtl' 'Mod' 'Sev']
['CollgCr' 'Veenker' 'Crawfor' 'NoRidge' 'Mitchel' 'Somerst' 'NWAmes'
 'OldTown' 'BrkSide' 'Sawyer' 'NridgHt' 'NAmes' 'SawyerW' 'IDOTRR'
 'MeadowV' 'Edwards' 'Timber' 'Gilbert' 'StoneBr' 'ClearCr' 'NPkVill'
 'Blmngtn' 'BrDale' 'SWISU' 'Blueste']
['Norm' 'Feedr' 'PosN' 'Artery' 'RRAe' 'RRNn' 'RRAn' 'PosA' 'RRNe']
['Norm' 'Artery' 'RRNn' 'Feedr' 'PosN' 'PosA' 'RRAn' 'RRAe']
['1Fam' '2fmCon' 'Duplex' 'TwnhsE' 'Twnhs']
['2Story' '1Story' '1.5Fin' '1.5Unf' 'SFoyer' 'SLvl' '2.5Unf' '2.5Fin']
['Gable' 'Hip' 'Gambrel' 'Mansard' 'Flat' 'Shed']
['CompShg' 'WdShngl' 'Metal' 'WdShake' 'Membran' 'Tar&Grv' 'Roll'
 'ClyTile']
['VinylSd' 'MetalSd' 'Wd Sdng' 'HdBoard' 'BrkFace' 'WdShing' 'CemntBd'
 'Plywood' 'AsbShng' 'Stucco' 'BrkComm' 'AsphShn' 'Stone' 'ImStucc'
 'CBlock' nan]
['VinylSd' 'MetalSd' 'Wd Shng' 'HdBoard' 'Plywood' 'Wd Sdng' 'CmentBd'
 'BrkFace' 'Stucco' 'AsbShng' 'Brk Cmn' 'ImStucc' 'AsphShn' 'Stone'
 'Other' 'CBlock' nan]
['BrkFace' 'None' 'Stone' 'BrkCmn' nan]
['Gd' 'TA' 'Ex' 'Fa']
['TA' 'Gd' 'Fa' 'Po' 'Ex']
['PConc' 'CBlock' 'BrkTil' 'Wood' 'Slab' 'Stone']
['Gd' 'TA' 'Ex' 'No Basement' 'Fa']
['TA' 'Gd' 'No Basement' 'Fa' 'Po']
['No' 'Gd' 'Mn' 'Av' 'No Basement']
['GLQ' 'ALQ' 'Unf' 'Rec' 'BLQ' 'No Basement' 'LwQ']
['Unf' 'BLQ' 'No Basement' 'ALQ' 'Rec' 'LwQ' 'GLQ']
['GasA' 'GasW' 'Grav' 'Wall' 'OthW' 'Floor']
['Ex' 'Gd' 'TA' 'Fa' 'Po']
['Y' 'N']
['SBrkr' 'FuseF' 'FuseA' 'FuseP' 'Mix' nan]
['Gd' 'TA' 'Ex' 'Fa' nan]
['Typ' 'Min1' 'Maj1' 'Min2' 'Mod' 'Maj2' 'Sev' nan]
['No Fireplace' 'TA' 'Gd' 'Fa' 'Ex' 'Po']
['Attchd' 'Detchd' 'BuiltIn' 'CarPort' 'No Garage' 'Basment' '2Types']
['RFn' 'Unf' 'Fin' 'No Garage']
['TA' 'Fa' 'Gd' 'No Garage' 'Ex' 'Po']
['TA' 'Fa' 'No Garage' 'Gd' 'Po' 'Ex']
['Y' 'N' 'P']
['No Pool' 'Ex' 'Fa' 'Gd']
['No Fence' 'MnPrv' 'GdWo' 'GdPrv' 'MnWw']
['None' 'Shed' 'Gar2' 'Othr' 'TenC']
['WD' 'New' 'COD' 'ConLD' 'ConLI' 'CWD' 'ConLw' 'Con' 'Oth' nan]
['Normal' 'Abnorml' 'Partial' 'AdjLand' 'Alloca' 'Family']

In [1038]:
# ordinal encoding
from sklearn.preprocessing import OrdinalEncoder, OneHotEncoder
colsOrdinal = ['LotShape', 'Utilities', 'LandSlope', 'HouseStyle', 'ExterQual', 'ExterCond', 'BsmtQual', 'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinType2', 'HeatingQC', 'CentralAir', 'KitchenQual', 'Functional', 'FireplaceQu', 'GarageFinish', 'GarageQual', 'GarageCond', 'PoolQC']
ordinal=OrdinalEncoder()
data[colsOrdinal] = pd.DataFrame(ordinal.fit_transform(data[colsOrdinal]),columns=colsOrdinal)
data.head()

,MSZoning,Street,Alley,LotShape,LandContour,Utilities,LotConfig,LandSlope,Neighborhood,Condition1,...,GarageType,GarageFinish,GarageQual,GarageCond,PavedDrive,PoolQC,Fence,MiscFeature,SaleType,SaleCondition
0,RL,Pave,No alley access,3.0,Lvl,0.0,Inside,0.0,CollgCr,Norm,...,Attchd,2.0,5.0,5.0,Y,3.0,No Fence,None,WD,Normal
1,RL,Pave,No alley access,3.0,Lvl,0.0,FR2,0.0,Veenker,Feedr,...,Attchd,2.0,5.0,5.0,Y,3.0,No Fence,None,WD,Normal
2,RL,Pave,No alley access,0.0,Lvl,0.0,Inside,0.0,CollgCr,Norm,...,Attchd,2.0,5.0,5.0,Y,3.0,No Fence,None,WD,Normal
3,RL,Pave,No alley access,0.0,Lvl,0.0,Corner,0.0,Crawfor,Norm,...,Detchd,3.0,5.0,5.0,Y,3.0,No Fence,None,WD,Abnorml
4,RL,Pave,No alley access,0.0,Lvl,0.0,FR2,0.0,NoRidge,Norm,...,Attchd,2.0,5.0,5.0,Y,3.0,No Fence,None,WD,Normal

In [1039]:
#one hot encoding 
cols = list(set(data.columns) - set(colsOrdinal))
oneHot=OneHotEncoder()
oneHotArr = oneHot.fit_transform(data[cols]).toarray()
labels = np.array(oneHot.get_feature_names_out()).ravel()
OneHotData = pd.DataFrame(oneHotArr, columns = labels, index = data.index)
OneHotData.head()

,RoofStyle_Flat,RoofStyle_Gable,RoofStyle_Gambrel,RoofStyle_Hip,RoofStyle_Mansard,RoofStyle_Shed,Heating_Floor,Heating_GasA,Heating_GasW,Heating_Grav,...,Condition1_RRNe,Condition1_RRNn,Condition2_Artery,Condition2_Feedr,Condition2_Norm,Condition2_PosA,Condition2_PosN,Condition2_RRAe,Condition2_RRAn,Condition2_RRNn
0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
1,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
2,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
3,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
4,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0

In [1040]:
#concat one hot with ordinal 
data=pd.concat([data[colsOrdinal],OneHotData],axis=1)
data

,LotShape,Utilities,LandSlope,HouseStyle,ExterQual,ExterCond,BsmtQual,BsmtCond,BsmtExposure,BsmtFinType1,...,Condition1_RRNe,Condition1_RRNn,Condition2_Artery,Condition2_Feedr,Condition2_Norm,Condition2_PosA,Condition2_PosN,Condition2_RRAe,Condition2_RRAn,Condition2_RRNn
0,3.0,0.0,0.0,5.0,2.0,4.0,2.0,4.0,3.0,2.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
1,3.0,0.0,0.0,2.0,3.0,4.0,2.0,4.0,1.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,5.0,2.0,4.0,2.0,4.0,2.0,2.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,5.0,3.0,4.0,4.0,1.0,3.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,5.0,2.0,4.0,2.0,4.0,0.0,2.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1454,3.0,0.0,0.0,2.0,2.0,4.0,2.0,4.0,3.0,2.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
1455,3.0,0.0,0.0,5.0,3.0,4.0,2.0,4.0,3.0,6.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
1456,3.0,0.0,0.0,2.0,3.0,4.0,2.0,4.0,3.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
1457,3.0,0.0,0.0,5.0,0.0,2.0,4.0,1.0,3.0,2.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
1458,3.0,0.0,0.0,2.0,3.0,4.0,4.0,4.0,2.0,2.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0

In [1041]:
X_train_cat=data.iloc[train_id]

In [1042]:
X_train_cat.shape

(1460, 193)

In [1043]:
X_test_cat=data.iloc[test_id]
X_test_cat

,LotShape,Utilities,LandSlope,HouseStyle,ExterQual,ExterCond,BsmtQual,BsmtCond,BsmtExposure,BsmtFinType1,...,Condition1_RRNe,Condition1_RRNn,Condition2_Artery,Condition2_Feedr,Condition2_Norm,Condition2_PosA,Condition2_PosN,Condition2_RRAe,Condition2_RRAn,Condition2_RRNn
0,3.0,0.0,0.0,5.0,2.0,4.0,2.0,4.0,3.0,2.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
1,3.0,0.0,0.0,2.0,3.0,4.0,2.0,4.0,1.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,5.0,2.0,4.0,2.0,4.0,2.0,2.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,5.0,3.0,4.0,4.0,1.0,3.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,5.0,2.0,4.0,2.0,4.0,0.0,2.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1454,3.0,0.0,0.0,2.0,2.0,4.0,2.0,4.0,3.0,2.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
1455,3.0,0.0,0.0,5.0,3.0,4.0,2.0,4.0,3.0,6.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
1456,3.0,0.0,0.0,2.0,3.0,4.0,2.0,4.0,3.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
1457,3.0,0.0,0.0,5.0,0.0,2.0,4.0,1.0,3.0,2.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
1458,3.0,0.0,0.0,2.0,3.0,4.0,4.0,4.0,2.0,2.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0

In [1044]:
X_train_cat.index=train_X_num.index
X_train= pd.concat([X_train_cat,train_X_num],axis=1)

In [1045]:
#test set
X_test_cat.index=test_X_num.index
X_test = pd.concat([X_test_cat,test_X_num],axis=1)
X_test.head()

,LotShape,Utilities,LandSlope,HouseStyle,ExterQual,ExterCond,BsmtQual,BsmtCond,BsmtExposure,BsmtFinType1,...,Condition2_PosA,Condition2_PosN,Condition2_RRAe,Condition2_RRAn,Condition2_RRNn,OverallQual,GrLivArea,GarageCars,GarageArea,TotalBsmtSF
0,3.0,0.0,0.0,5.0,2.0,4.0,2.0,4.0,3.0,2.0,...,0.0,0.0,0.0,0.0,0.0,5,896,1.0,730.0,882.0
1,3.0,0.0,0.0,2.0,3.0,4.0,2.0,4.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,6,1329,1.0,312.0,1329.0
2,0.0,0.0,0.0,5.0,2.0,4.0,2.0,4.0,2.0,2.0,...,0.0,0.0,0.0,0.0,0.0,5,1629,2.0,482.0,928.0
3,0.0,0.0,0.0,5.0,3.0,4.0,4.0,1.0,3.0,0.0,...,0.0,0.0,0.0,0.0,0.0,6,1604,2.0,470.0,926.0
4,0.0,0.0,0.0,5.0,2.0,4.0,2.0,4.0,0.0,2.0,...,0.0,0.0,0.0,0.0,0.0,8,1280,2.0,506.0,1280.0

### Finding top correlation with saleprice

In [1046]:
data=X_train.corr().sort_values(by='SalePrice',ascending=False)['SalePrice']
data[:15]

SalePrice                1.000000
OverallQual              0.790982
GrLivArea                0.708624
GarageCars               0.640409
GarageArea               0.623431
TotalBsmtSF              0.613581
Foundation_PConc         0.497734
Neighborhood_NridgHt     0.402149
SaleType_New             0.357509
SaleCondition_Partial    0.352060
GarageType_Attchd        0.335961
MasVnrType_Stone         0.330476
Neighborhood_NoRidge     0.330424
Exterior2nd_VinylSd      0.306389
Exterior1st_VinylSd      0.305009
Name: SalePrice, dtype: float64

### Taking features which has corr greater than 0.60

In [1047]:
#separate labels from training set 
Y_train=pd.DataFrame(X_train['SalePrice'],columns=['SalePrice'])
print(Y_train.head())
X_train=X_train[['OverallQual','GrLivArea','Foundation_PConc','Neighborhood_NridgHt']]
X_train.info()

   SalePrice
0     208500
1     181500
2     223500
3     140000
4     250000
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 4 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   OverallQual           1460 non-null   int64
 1   GrLivArea             1460 non-null   int64
 2   Foundation_PConc      1460 non-null   float64
 3   Neighborhood_NridgHt  1460 non-null   float64
dtypes: float64(2), int64(2)
memory usage: 45.8 KB

In [1048]:
X_test=X_test[['OverallQual','GrLivArea','Foundation_PConc','Neighborhood_NridgHt']]
X_test

      OverallQual  GrLivArea  Foundation_PConc  Neighborhood_NridgHt
0               5        896               1.0                   0.0
1               6       1329               0.0                   0.0
2               5       1629               1.0                   0.0
3               6       1604               0.0                   0.0
4               8       1280               1.0                   0.0
...           ...        ...               ...                   ...
1454            4       1092               1.0                   0.0
1455            4       1092               1.0                   0.0
1456            5       1224               0.0                   0.0
1457            5        970               0.0                   0.0
1458            7       2000               0.0                   0.0

[1459 rows x 4 columns]

## Applying normalization

In [1049]:
def normalize(train,test):
    train_normalized = train.copy()
    test_normalized = test.copy()
    
    
    for column in train_normalized.columns:
        mini=min(train_normalized[column].min(),test_normalized[column].min())
        maxi = max(train_normalized[column].max(),test_normalized[column].max())
    
        
        train_normalized[column] = (train_normalized[column]- mini) / (maxi-mini)
        test_normalized[column] = (test_normalized[column]- mini) / (maxi-mini)
    return train_normalized,test_normalized

In [1050]:
#Apply data normalization 
cols = X_train.columns
train,test = normalize(X_train,X_test)
X_train = pd.DataFrame(train,columns=cols)
X_test = pd.DataFrame(test,columns=cols)
print(X_train.head())
print(X_test.head())

   OverallQual  GrLivArea  Foundation_PConc  Neighborhood_NridgHt
0     0.666667   0.259231               1.0                   0.0
1     0.555556   0.174830               0.0                   0.0
2     0.666667   0.273549               1.0                   0.0
3     0.666667   0.260550               0.0                   0.0
4     0.777778   0.351168               1.0                   0.0
   OverallQual  GrLivArea  Foundation_PConc  Neighborhood_NridgHt
0     0.444444   0.105878               1.0                   0.0
1     0.555556   0.187453               0.0                   0.0
2     0.444444   0.243971               1.0                   0.0
3     0.555556   0.239261               0.0                   0.0
4     0.777778   0.178222               1.0                   0.0

In [1051]:
X_train.shape,X_test.shape,Y.shape

((1460, 4), (1459, 4), (1460,))

## Dealing with missing value if any

In [1052]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(X_train)
X_train = imputer.transform(X_train)

In [1053]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(X_test)
X_test = imputer.transform(X_test)

## Linear Regression Model

In [1071]:
# Train.csv has been split because to find the performance metrics
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
X_train_Prep, X_val, Y_train_Prep, Y_val = train_test_split(X_train,Y, test_size = 0.2, random_state=0)

In [1072]:
from sklearn.linear_model import LinearRegression
#Applying MultiRegression
Multi_reg = LinearRegression()
Multi_reg.fit(X_train_Prep,Y_train_Prep )

LinearRegression()

In [1073]:
y_pred = Multi_reg.predict(X_val)

In [1074]:
y_pred = pd.DataFrame(y_pred,columns=['SalePrice'])

In [1075]:
y_pred

         SalePrice
0    244730.263690
1    173699.373932
2    124684.707590
3    226945.798124
4    143893.079506
..             ...
287  247943.688591
288  390484.800626
289  231840.047009
290   68310.462378
291  119042.363790

[292 rows x 1 columns]

## Performace of Model

In [1076]:
from sklearn.metrics import r2_score
def CostFunction(y_pred, Y_test):
    y_pred = y_pred.squeeze()
    y_val = Y_test.squeeze()
    print("Mean square error (MSE): %.2f" % np.mean((y_pred - y_val) ** 2))
    print("Root mean square error (RMSE): %.2f" % np.sqrt(np.mean((y_pred - y_val) ** 2)))
    print("Mean absolute error (MAE): %.2f" % np.mean(abs(y_pred - y_val)))
    print("Coefficient of determination (R^2): %.2f" % r2_score(y_val, y_pred))

CostFunction(y_pred, Y_val)

Mean square error (MSE): 14318471285.06
Root mean square error (RMSE): 119659.81
Mean absolute error (MAE): 92938.94
Coefficient of determination (R^2): 0.70

## Testing with test.csv

In [1077]:
Y_Final=Multi_reg.predict(X_test)

In [1068]:
Y_Final=pd.DataFrame(Y_Final)

In [1069]:
Y_Final

                  0
0     119421.296391
1     158428.247776
2     164376.057325
3     175293.949354
4     221019.895890
...             ...
1454  105425.959509
1455  105425.959509
1456  125972.633893
1457  110394.858617
1458  225596.541998

[1459 rows x 1 columns]

## Finding RSMLE

In [1081]:
from sklearn.metrics import mean_squared_log_error

def compute_rmsle(Y_val: np.ndarray, y_pred: np.ndarray, precision: int = 2) -> float:
    rmsle = np.sqrt(mean_squared_log_error(Y_val, y_pred))
    return round(rmsle, precision)

In [1082]:
compute_rmsle(Y_val,y_pred)

0.21